### ISSUE TITLE
consumer & access token keys are exposed

### ISSUE THREAD

**Issue by Defcon27** [vinitshahdeo/jobtweets#27]
The keys used to authenticate with Twitter API are exposed. I think you already know this but you might forgot to .gitignore the personal keys. Its not safe to expose these keys out as recommended by twitter. 

Just a suggestion 🙃 🤗

**Comment by vinitshahdeo** [comment]
@Defcon27 Thanks for reporting. Those access tokens are revoked before pushing 😅

**Comment by Defcon27** [comment]
Oh I didn't know that lol
